language: java
git:
  submodules: false
sudo: required

before_install:
  - sudo apt-get install libx11-dev
  - cd ..
  - git clone --recurse-submodules git://jogamp.org/srv/scm/gluegen.git gluegen
  - pushd gluegen/make
  - ant
  - popd

install:
  - pushd jogl/make
  - ant
  - ant junit.run
