language: java
git:
  submodules: false

before_install:
  - cd ..
  - git clone --recurse-submodules git://jogamp.org/srv/scm/gluegen.git gluegen
  - pusdh gluegen/make
  - ant
  - popd

install:
  - pusdh jogl/make
  - ant
  - ant junit.run
